name: WakaTime Stats Update

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # chạy mỗi ngày lúc 0h UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check if README has changed
        run: |
          git diff
          git diff --quiet || echo "::set-output name=changed::true"
        id: check_diff

      - name: Commit changes
        if: steps.check_diff.outputs.changed == 'true'
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Update README with latest WakaTime stats"
          git push

      - name: Update WakaTime Readme
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          SHOW_LANGUAGE: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_PROJECTS: true
          SHOW_EDITORS: true
          SHOW_OS: true
          SHOW_TIMEZONE: true
          SHOW_COMMIT: true

          COMMIT_MESSAGE: "Updated wakatime-stats graph with new metrics"
          COMMIT_USERNAME: "GitHubActionBot"
          COMMIT_EMAIL: "action-bot@github.org"
