name: Test Secrets

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret (should be masked)
        run: echo "Secret length is ${#WAKATIME_API_KEY}"
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
