name: WakaTime Stats Update

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Update WakaTime Readme
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ github.token }}

          SHOW_LANGUAGE: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_PROJECTS: true
          SHOW_EDITORS: true
          SHOW_OS: true
          SHOW_TIMEZONE: true
          SHOW_COMMIT: true

          COMMIT_MESSAGE: "Updated wakatime-stats graph with new metrics"
          COMMIT_USERNAME: "GitHubActionBot"
          COMMIT_EMAIL: "action-bot@github.org"
