name: WakaTime Stats Update

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          
          API_BASE_URL: https://wakatime.com/api
          SHOW_TITLE: true
          SECTION_NAME: waka
          CODE_LANG: all_time 
          TIME_RANGE: true
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: true

          COMMIT_MESSAGE: Updated wakatime-stats graph with new metrics
          TARGET_BRANCH: main
          TARGET_PATH: README.md

          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.org
          AUTHOR_NAME: hieuvuanguday
          AUTHOR_EMAIL: hieuvuanguday.dev@gmail.com
