name: WakaTime Stats Update

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Chạy lúc 0h UTC hàng ngày (7h sáng VN)
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme-stats@v2.1.0
        with:
          # 🔐 WakaTime API Key – bạn phải tạo secret tên `WAKATIME_API_KEY`
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          
          # ⚙️ Cấu hình hiển thị
          API_BASE_URL: https://wakatime.com/api
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: ->
          CODE_LANG: all_time 
          TIME_RANGE: true
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: true

          # 📝 Commit vào README.md
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics
          TARGET_BRANCH: main
          TARGET_PATH: README.md

          # 🧑 Tác giả commit là bạn, người thực hiện commit là GitHub Bot
          COMMITTER_NAME: GitHub Action
          COMMITTER_EMAIL: actions@github.com
          AUTHOR_NAME: hieuvuanguday
          AUTHOR_EMAIL: hieuvuanguday.dev@gmail.com
