name: WakaTime Stats Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # chạy mỗi ngày vào lúc 0h UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update WakaTime Readme
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LANGUAGE: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_PROJECTS: true
          SHOW_EDITORS: true
          SHOW_OS: true
          SHOW_TIMEZONE: true
          SHOW_COMMIT: true
